---
- name: Adding postgresql repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Adding postgresql repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename }}-pgdg main"

- name: Installing postgresql
  apt:
    name:
      - postgresql-11
      - python-psycopg2
      - libpq-dev

- name: Creating postgresql uservagrant
  postgresql_user:
    name: vagrant
    password: "vagrant"
    role_attr_flags: SUPERUSER,LOGIN
  become_user: postgres

- name: Creating the vagrant database
  postgresql_db:
    name: vagrant
  become_user: postgres

- name: Creating the wfrp database
  postgresql_db:
    name: wfrp
  become_user: postgres

- name: Creating the wfrp_test database
  postgresql_db:
    name: wfrp_test
  become_user: postgres

- name: Configuring postgresql settings
  copy:
    src: postgresql.auto.conf
    dest: /var/lib/postgresql/11/main/postgresql.auto.conf
    owner: postgres
    group: postgres
    mode: 0600
  notify: restart postgresql

- name: Configuring postgresql access
  copy:
    src: pg_hba.conf
    dest: /etc/postgresql/11/main/pg_hba.conf
  notify: restart postgresql

- name: Configuring postgresql quick access via psql
  copy:
    src: .pgpass
    dest: /home/vagrant/.pgpass
    mode: 0600
  become_user: vagrant
