---
- name: Install curl
  apt: name=curl state=present

- name: Checking node install
  shell: node --version | sed -e 's/^v12.*$/12/'
  register: node_version
  ignore_errors: true
  changed_when: false

- name: Adding source for node 12
  command: bash -c "curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -"
  when: node_version.stdout is not search('12')

- name: Install node
  apt: name=nodejs state=present
