---
- name: Add sury repository key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg

- name: Add php's ppa
  apt_repository:
    repo: deb https://packages.sury.org/php/ {{ ansible_lsb.codename }} main

- name: Install php-fpm and modules
  apt:
    name:
      - php7.4
      - php7.4-curl
      - php7.4-fpm
      - php7.4-intl
      - php7.4-mbstring
      - php7.4-pgsql
      - php7.4-redis
      - php7.4-xml
      - php7.4-xdebug
      - php7.4-zip

- name: Disable default pool
  command: mv /etc/php/7.4/fpm/pool.d/www.conf /etc/php/7.4/fpm/pool.d/www.disabled creates=/etc/php/7.4/fpm/pool.d/www.disabled
  notify: restart web services

- name: Copy php-fpm configuration
  template:
    src: php-fpm.conf.j2
    dest: /etc/php/7.4/fpm/pool.d/www.conf
  notify: restart web services

- name: Overriding php.ini configurations
  template:
    src: 99_php_custom.ini.j2
    dest: "{{ item }}"
  with_items:
    - /etc/php/7.4/cli/conf.d/99_php_custom.ini
    - /etc/php/7.4/fpm/conf.d/99_php_custom.ini

- name: Disable xdebug by default
  lineinfile:
    dest: "{{ item }}"
    state: present
    regexp: "zend_extension=xdebug.so"
    line: "#zend_extension=xdebug.so"
  with_items:
    - /etc/php/7.4/cli/conf.d/20-xdebug.ini
    - /etc/php/7.4/fpm/conf.d/20-xdebug.ini
  notify: restart web services

- name: Check if Composer is installed.
  stat: "path=/usr/local/bin/composer"
  register: composer_bin

- name: Get Composer installer signature.
  uri:
    url: https://composer.github.io/installer.sig
    return_content: yes
  register: composer_installer_signature
  when: not composer_bin.stat.exists

- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
    checksum: "sha384:{{ composer_installer_signature.content }}"
  when: not composer_bin.stat.exists

- name: Run Composer installer.
  command: php composer-installer.php --filename=composer --install-dir=/usr/local/bin chdir=/tmp
  when: not composer_bin.stat.exists
